### ISSUE TITLE
Add Sörmlands museum

### ISSUE THREAD

**Issue by Abbe98** [Ambrosiani/Swedish-GLAMwiki-stats#1]
Tracking category: `Category:Collections_of_Sörmlands_museum`

**Comment by Abbe98** [comment]
Closed by 3c14c00ff72ab20f3f32e5794aeffb6d18f361ac :100:

**Comment by Ambrosiani** [comment]
ja jag insåg misstaget typ 1 min efter att jag tweetat klart! @Abbe98
